name: entrance_test
description: A new Flutter project.
publish_to: 'none'
version: 18.1.20+30

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  ansicolor: ^2.0.2
  cached_network_image: ^3.3.1
  carousel_slider: ^4.2.1
  dio: ^5.4.3+1
  dynamic_height_grid_view: ^0.0.4
  flutter:
    sdk: flutter

  get: ^4.6.6
  get_storage: ^2.1.1
  intl: ^0.19.0
  package_info_plus: ^8.0.0
  talker_dio_logger: ^4.2.0
  change_app_package_name: ^1.2.0
  rename_app: ^1.5.0
  google_fonts: ^6.2.1
  flutter_markdown: ^0.7.2
  image_picker: ^1.0.2
  sqflite: ^2.3.3+1
  path: ^1.8.0
  path_provider: ^2.0.2
  permission_handler: ^8.0.0+2
  webview_flutter: ^4.8.0
  intl_phone_field: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
